---
version: '3.5'
services:

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - ../connect-mqtt-source/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../connect-mqtt-source/password:/etc/mosquitto/passwd

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - mosquitto