---
version: '3.5'
services:
  solace:
    image: solace/solace-pubsub-standard:9.1.0.77
    hostname: solace
    container_name: solace
    volumes:
      - ../../connect/connect-jms-solace-sink/show_queue_cmd:/usr/sw/jail/cliscripts/show_queue_cmd
    ports:
      - 8080:8080
      - 55555:55555
      - 5550:5550
    tmpfs: /dev/shm
    ulimits:
      nofile:
        soft: 2448
        hard: 38048
    environment:
      username_admin_globalaccesslevel: admin
      username_admin_password: admin
      system_scaling_maxconnectioncount: 100

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - solace
    volumes:
        - ../../connect/connect-jms-solace-sink/sol-jms-10.6.0.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink/lib/sol-jms-10.6.0.jar
        #- ../../connect/connect-jms-solace-sink/commons-lang-2.6.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink/lib/commons-lang-2.6.jar # bug

