---
version: '3.5'
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    volumes:
      - ../connect-debezium-source/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ../connect-debezium-source/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: 172.%  # Allow docker containers to connect to mysql
      
  postgres:
    image: debezium/postgres:10.0
    hostname: postgres
    container_name: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ../connect-debezium-source/customers.sql:/docker-entrypoint-initdb.d/z99_dump.sql

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - mysql
    volumes:
      - ../connect-jdbc-source/mysql-connector-java-5.1.45-bin.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/mysql-connector-java-5.1.45-bin.jar
