---
version: '3.5'
services:
  connect:
    volumes:
      - secret:/var/lib/secret
      - ../../environment/kerberos/kdc/krb5.conf:/etc/krb5.conf
      - ../../connect/connect-gcs-sink/keyfile.json:/root/keyfiles/keyfile.json:ro