---
version: '3.5'
services:
  connect:
    volumes:
        - $HOME/.aws/credentials:/root/.aws/credentials:ro
        - $HOME/.aws/config:/root/.aws/config:ro
        - ../../environment/sasl-ssl/security:/etc/kafka/secrets