name: Run Regression Tests

# on:
  # push:

  # schedule:
  #   - cron: '0 0 * * 0' # weekly
on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing with ${{ matrix.tag }} ${{ matrix.test_list }}
    strategy:
      matrix:
        tag: [ "6.0.0"]
        test_list : [
                      "connect/connect-salesforce-bulkapi-sink connect/connect-salesforce-bulkapi-source",
                      "connect/connect-salesforce-bulkapi-sink connect/connect-salesforce-bulkapi-source"
                    ]
    env:
      TRAVIS_JOB_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decrypt secrets.tgz
        run: ./.github/scripts/decrypt_secret.sh
        env:
          SECRETS_ENCRYPTION_PASSWORD: ${{ secrets.SECRETS_ENCRYPTION_PASSWORD }}

      - name: Build and Test
        run: bash scripts/run-tests.sh "${{ matrix.test_list }}" "${{ matrix.tag }}"
